export const endpoints = {
  home: '/',
  contact: '/contact',
  login: 'auth/login',
  register: 'auth/register',
  logout: 'auth/logout',
  refreshAccessToken: 'auth/refresh',
  articles: 'article',
  addArticle: 'article/add',
  deleteArticle: 'article/delete',
  likeArticle: 'article/like/',
  countComments: 'article/comments/count',
  userArticle: '/user/article',
  userProfile: 'user/profile',
  userSettings: 'user/settings',
  userUploadPicture: 'upload/avatar',
};
